config/routes.rb
Rails.application.routes.draw do
  resources :substrings
  # get 'substrings/new'
  # get 'substrings/create'
  # get 'inputs/new'
  # get 'inputs/create'
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  root to: "substrings#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/input.rb
class Input < ApplicationRecord
end

app/models/substring.rb
class Substring < ApplicationRecord

  def find_pattern(s)
h = {}
    d = -1
    max = 0
    count = 0

    (0...s.length).each do |i|
      if h[s[i]].nil?
        count += 1
      else
        max = count if count > max
        count = h[s[i]] > d ? i - h[s[i]] : count + 1
        d = h[s[i]] if d < h[s[i]]
      end
      h[s[i]] = i
    end

    max < count ? count : max
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  def new
    @inputs= Inputs.new
  end

  def create
    @inputs=Inputs.new(inputs_params)
  end
end

app/controllers/substrings_controller.rb
class SubstringsController < ApplicationController
  def new
    @substring = Substring.new
  end

  def index
@substrings = Substring.all
  end

  def show
  end

  def create
    @sol=Solution.new
    @substring = Substring.new(substring_params)
    @res = @sol.find_pattern(@substring.str1)
    # @substring.result_digits = @res
    @substring.result_str=@res
    @substring.result_digits=@res.length
    if  @substring.save
    redirect_to substrings_path
    else
    render 'new'
    end
  end

  def search_substring(s)
    # h = {}
    # d = -1
    # max = 0
    # count = 0

    # (0...s.length).each do |i|
    #   if h[s[i]].nil?
    #     count += 1
    #   else
    #     max = count if count > max
    #     count = h[s[i]] > d ? i - h[s[i]] : count + 1
    #     d = h[s[i]] if d < h[s[i]]
    #   end
    #   h[s[i]] = i
    # end

    # max < count ? count : max
  end



  def substring_params
    params.require(:substring).permit(:str1, :str2)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/substrings_helper.rb
module SubstringsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
# <% name = current_user.present? ? current_user.email : 'Stranger' %>

<h1>Welcome, <%= name %> </h1>
<p>Find me in app/views/home/index.html.erb</p>

# <div class="container">
#   <div class="py-5">
#     <div class="card">
#       <div class="card-body">
#       <h4 class="card-title"> Enter URL to shorten </h4>
#       <%= form_with ( @substring) do  |f| %>
#         <%= f.label :str1 %><br>
#           <%= f.text_field :str1, class: "form-control",
#           placeholder: "Enter String" %>
#           <%= f.label :str2 %><br>
#           <%= f.text_field :str2, class: "form-control",
#           placeholder: "Enter pattern to search" %>
#           <%= f.submit "Search", class: 'btn btn-primary mt-2' %>
#       <% end %>
#       </div>
#       <div class="card-body">
#         <div id="error-message">

#         </div>
#       </div>

#       # <div class="card-body">
#       # <h4 class="card-title"> The Shortened Url: </h4>
#       #   <div  data-controller="clipboard">
#       #     <input id="short-link" data-clipboard-target="source"  type="text"  readonly>
#       #   <button data-action="clipboard#copy" class="btn btn-success">Copy </button>
#       #   </div>
#       # </div>
#     </div>
#   </div>
    
 


  
# </div>

app/views/inputs/create.html.erb
<h1>Inputs#create</h1>
<p>Find me in app/views/inputs/create.html.erb</p>

app/views/inputs/new.html.erb
<h1>Inputs#new</h1>
<p>Find me in app/views/inputs/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSubstring</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">LogIn App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/substrings/create.html.erb
<h1>Substrings#create</h1>
<p>Find me in app/views/substrings/create.html.erb</p>

app/views/substrings/index.html.erb
<h1> result </h1>

<%= button_to "Add new substring", new_substring_path, method: :get %>
<ul>
  <% @substrings.each do |substring| %>
    <li><%= link_to substring.str2, new_substring_path(substring) %></li>
  <%end%>
<ul>


app/views/substrings/new.html.erb
<h1>Substrings#new</h1>
<p>Find me in app/views/substrings/new.html.erb</p>
 <div class="card-body">
      <h4 class="card-title"> Enter URL to shorten </h4>
      <%= form_for(@substring) do  |f| %>
        <%= f.label :str1 %><br>
          <%= f.text_field :str1, class: "form-control",
          placeholder: "Enter String" %>
          <%= f.label :str2 %><br>
          <%= f.text_field :str2, class: "form-control",
          placeholder: "Enter pattern to search" %>
          <%= f.submit "Search", class: 'btn btn-primary mt-2' %>
      <% end %>
      </div>

app/views/substrings/show.html.erb
<h1> show </h1>